GET http://localhost:3000/api/leftcol


### 

POST http://localhost:3000/api/leftcol
Content-Type: application/json

{
    "amount": -23,
    "reason": "Mua đồ chơi ở ProzipLand",
    "date": "2025-01-08"
}

###

GET http://localhost:3000/api/leftcol/2025/01

### 

GET http://localhost:3000/api/rightcol


### 

POST http://localhost:3000/api/rightcol
Content-Type: application/json

{
    "amount": -23,
    "reason": "Mua đồ chơi ở ProzipLand",
    "date": "2025-01-08"
}

###

GET http://localhost:3000/api/rightcol/2025/01

